### PR TITLE
Update environment.js

### PR DESCRIPTION
**Pull request by mikkel1156**
Fix for #64 to remove the hardcoded URL, making it just use a relative one instead.

### CODE REVIEW

**Comment by edufschmidt** [comment]
Hi, would you please make a PR to `dev` instead? Thanks!

**Comment by mikkel1156** [comment]
Seems that dev is actually behind master, do you want me to make a new PR using `dev` (since I made the changes in `master` for my fork), or is this fine with you?

**Comment by edufschmidt** [comment]
If that's not too much trouble, it would be nice. Thanks!

**Comment by mikkel1156** [comment]
New PR at #69

**Pull request closed without merging**
